[build]
  command = "GIT_SSH_COMMAND=\"ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no\" git submodule update --init --remote && npm run build"

[build.environment]
  NODE_ENV = "production"
  NODE_VERSION = "14"

[[redirects]]
  from = "/blog/"
  to = "/"
  status = 302
