[build]
  command = "bash ./netlify-setup.sh && GIT_SSH_COMMAND=\"ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no\" git submodule update --init --remote && npm run build"

[build.environment]
  NODE_ENV = "production"
  NODE_VERSION = "14"

[[redirects]]
  from = "/blog/"
  to = "/"
  status = 302
[[redirects]]
  from = "/blog/episerver-how-to-change-a-contents-modified-date-programmatically/"
  to = "/blog/episerver-how-to-change-contents-modified-date-programmatically/"
  status = 301
