name: Daily Netlify build trigger

on:
  schedule:
    # Runs at 09:00 UTC every day
    - cron: '0 9 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Curl request to Netlify's build hook
        env:
          # Dunno if the URL should be kept secret but it shouldn't hurt either
          NETLIFY_BUILD_HOOK: ${{ secrets.NETLIFY_BUILD_HOOK }}
        run: curl -X POST -d {} "$NETLIFY_BUILD_HOOK"
